// MIT License
//  
//  Copyright (c) 2021 Filip Liwiński
//  
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//  
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//  
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
//

using System.ComponentModel;

namespace SendIt.HtmlBuilder
{
    public enum StyleProperty
    {
        [Description("align-content")]
        AlignContent,
        [Description("align-items")]
        AlignItems,
        [Description("align-self")]
        AlignSelf,
        [Description("animation")]
        Animation,
        [Description("animation-delay")]
        AnimationDelay,
        [Description("animation-direction")]
        AnimationDirection,
        [Description("animation-duration")]
        AnimationDuration,
        [Description("animation-fill-mode")]
        AnimationFillMode,
        [Description("animation-iteration-count")]
        AnimationIterationCount,
        [Description("animation-name")]
        AnimationName,
        [Description("animation-play-state")]
        AnimationPlayState,
        [Description("animation-timing-function")]
        AnimationTimingFunction,
        [Description("backface-visibility")]
        BackfaceVisibility,
        [Description("background")]
        Background,
        [Description("background-attachment")]
        BackgroundAttachment,
        [Description("background-clip")]
        BackgroundClip,
        [Description("background-color")]
        BackgroundColor,
        [Description("background-image")]
        BackgroundImage,
        [Description("background-origin")]
        BackgroundOrigin,
        [Description("background-position")]
        BackgroundPosition,
        [Description("background-repeat")]
        BackgroundRepeat,
        [Description("background-size")]
        BackgroundSize,
        [Description("border")]
        Border,
        [Description("border-bottom")]
        BorderBottom,
        [Description("border-bottom-color")]
        BorderBottomColor,
        [Description("border-bottom-left-radius")]
        BorderBottomLeftRadius,
        [Description("border-bottom-right-radius")]
        BorderBottomRightRadius,
        [Description("border-bottom-style")]
        BorderBottomStyle,
        [Description("border-bottom-width")]
        BorderBottomWidth,
        [Description("border-collapse")]
        BorderCollapse,
        [Description("border-color")]
        BorderColor,
        [Description("border-image")]
        BorderImage,
        [Description("border-image-outset")]
        BorderImageOutset,
        [Description("border-image-repeat")]
        BorderImageRepeat,
        [Description("border-image-slice")]
        BorderImageSlice,
        [Description("border-image-source")]
        BorderImageSource,
        [Description("border-image-width")]
        BorderImageWidth,
        [Description("border-left")]
        BorderLeft,
        [Description("border-left-color")]
        BorderLeftColor,
        [Description("border-left-style")]
        BorderLeftStyle,
        [Description("border-left-width")]
        BorderLeftWidth,
        [Description("border-radius")]
        BorderRadius,
        [Description("border-right")]
        BorderRight,
        [Description("border-right-color")]
        BorderRightColor,
        [Description("border-right-style")]
        BorderRightStyle,
        [Description("border-right-width")]
        BorderRightWidth,
        [Description("border-spacing")]
        BorderSpacing,
        [Description("border-style")]
        BorderStyle,
        [Description("border-top")]
        BorderTop,
        [Description("border-top-color")]
        BorderTopColor,
        [Description("border-top-left-radius")]
        BorderTopLeftRadius,
        [Description("border-top-right-radius")]
        BorderTopRightRadius,
        [Description("border-top-style")]
        BorderTopStyle,
        [Description("border-top-width")]
        BorderTopWidth,
        [Description("border-width")]
        BorderWidth,
        [Description("bottom")]
        Bottom,
        [Description("box-shadow")]
        BoxShadow,
        [Description("box-sizing")]
        BoxSizing,
        [Description("caption-side")]
        CaptionSide,
        [Description("clear")]
        Clear,
        [Description("clip")]
        Clip,
        [Description("color")]
        Color,
        [Description("column-count")]
        ColumnCount,
        [Description("column-fill")]
        ColumnFill,
        [Description("column-gap")]
        ColumnGap,
        [Description("column-rule")]
        ColumnRule,
        [Description("column-rule-color")]
        ColumnRuleColor,
        [Description("column-rule-style")]
        ColumnRuleStyle,
        [Description("column-rule-width")]
        ColumnRuleWidth,
        [Description("column-span")]
        ColumnSpan,
        [Description("column-width")]
        ColumnWidth,
        [Description("columns")]
        Columns,
        [Description("content")]
        Content,
        [Description("counter-increment")]
        CounterIncrement,
        [Description("counter-reset")]
        CounterReset,
        [Description("cursor")]
        Cursor,
        [Description("direction")]
        Direction,
        [Description("display")]
        Display,
        [Description("empty-cells")]
        EptyCells,
        [Description("flex")]
        Flex,
        [Description("flex-basis")]
        FlexBasis,
        [Description("flex-direction")]
        FlexDirection,
        [Description("flex-flow")]
        FlexFlow,
        [Description("flex-grow")]
        FlexGrow,
        [Description("flex-shrink")]
        FlexShrink,
        [Description("flex-wrap")]
        FlexWrap,
        [Description("float")]
        Float,
        [Description("font")]
        Font,
        [Description("font-family")]
        FontFamily,
        [Description("font-size")]
        FontSize,
        [Description("font-size-adjust")]
        FontSizeAdjust,
        [Description("font-stretch")]
        FontStretch,
        [Description("font-style")]
        FontStyle,
        [Description("font-variant")]
        FontVariant,
        [Description("font-weight")]
        FontWeight,
        [Description("height")]
        Height,
        [Description("justify-content")]
        JustifyContent,
        [Description("left")]
        Left,
        [Description("letter-spacing")]
        LetterSpacing,
        [Description("line-height")]
        LineHeight,
        [Description("list-style")]
        ListStyle,
        [Description("list-style-image")]
        ListStyleImage,
        [Description("list-style-position")]
        ListStylePosition,
        [Description("list-style-type")]
        ListStyleType,
        [Description("margin")]
        Margin,
        [Description("margin-bottom")]
        MarginBottom,
        [Description("margin-left")]
        MarginLeft,
        [Description("margin-right")]
        MarginRight,
        [Description("margin-top")]
        MarginTop,
        [Description("max-height")]
        MaxHeight,
        [Description("max-width")]
        MaxWidth,
        [Description("min-height")]
        MinHeight,
        [Description("min-width")]
        MinWidth,
        [Description("opacity")]
        Opacity,
        [Description("order")]
        Order,
        [Description("outline")]
        Outline,
        [Description("outline-color")]
        OutlineColor,
        [Description("outline-offset")]
        OutlineOffset,
        [Description("outline-style")]
        OutlineStyle,
        [Description("outline-width")]
        OutlineWidth,
        [Description("overflow")]
        Overflow,
        [Description("overflow-x")]
        OverflowX,
        [Description("overflow-y")]
        OverflowY,
        [Description("padding")]
        Padding,
        [Description("padding-bottom")]
        PaddingBottom,
        [Description("padding-left")]
        PaddingLeft,
        [Description("padding-right")]
        PaddingRight,
        [Description("padding-top")]
        PaddingTop,
        [Description("page-break-after")]
        PageBreakAfter,
        [Description("page-break-before")]
        PageBreakBefore,
        [Description("page-break-inside")]
        PageBreakInside,
        [Description("perspective")]
        Perspective,
        [Description("perspective-origin")]
        PerspectiveOrigin,
        [Description("position")]
        Position,
        [Description("quotes")]
        Quotes,
        [Description("resize")]
        Resize,
        [Description("right")]
        Right,
        [Description("tab-size")]
        TabSize,
        [Description("table-layout")]
        TableLayout,
        [Description("text-align")]
        TextAlign,
        [Description("text-align-last")]
        TextAlignLast,
        [Description("text-decoration")]
        TextDecoration,
        [Description("text-decoration-color")]
        TextDecorationColor,
        [Description("text-decoration-line")]
        TextDecorationLine,
        [Description("text-decoration-style")]
        TextDecorationStyle,
        [Description("text-indent")]
        TextIndent,
        [Description("text-justify")]
        TextJustify,
        [Description("text-overflow")]
        TextOverflow,
        [Description("text-shadow")]
        TextShadow,
        [Description("text-transform")]
        TextTransform,
        [Description("top")]
        Top,
        [Description("transform")]
        Transform,
        [Description("transform-origin")]
        TransformOrigin,
        [Description("transform-style")]
        TransformStyle,
        [Description("transition")]
        Transition,
        [Description("transition-delay")]
        TransitionDelay,
        [Description("transition-duration")]
        TransitionDuration,
        [Description("transition-property")]
        TransitionProperty,
        [Description("transition-timing-function")]
        TransitionTimingFunction,
        [Description("vertical-align")]
        VerticalAlign,
        [Description("visibility")]
        Visibility,
        [Description("white-space")]
        WhiteSpace,
        [Description("width")]
        Width,
        [Description("word-break")]
        WordBreak,
        [Description("word-spacing")]
        WordSpacing,
        [Description("word-wrap")]
        WordWrap,
        [Description("z-index")]
        ZIndex

    }
}
