trigger: none

pr:
- master
- develop

pool:
  vmImage: windows-2019

resources:
  repositories:
  - repository: templates
    type: git
    name: GitHub.Public/YAML.Templates
    ref: $(templates_branch)

steps:
  - template: build.pr.yml@templates
    parameters:
      projectName: SendIt.HtmlBuilder
      unitTestsProjectName: SendIt.HtmlBuilder.Tests
      sonarCloudProjectKey: filipliwinski_SendIt.HtmlBuilder
